// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVXnUG9hcRu2bn2PukWFQmCJ9-eJU1OME',
    appId: '1:689893375587:web:cd2f59d093e539731a4256',
    messagingSenderId: '689893375587',
    projectId: 'demo1-2ad94',
    authDomain: 'demo1-2ad94.firebaseapp.com',
    storageBucket: 'demo1-2ad94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBha5O2KiUdN-vIrE_U3Mq_vEaupjd5pBU',
    appId: '1:689893375587:android:0495a1d10c6685bb1a4256',
    messagingSenderId: '689893375587',
    projectId: 'demo1-2ad94',
    storageBucket: 'demo1-2ad94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHvmV6RejMeqxTTbMlmqrlCzp7F7pThk',
    appId: '1:689893375587:ios:95d2afa289d53c811a4256',
    messagingSenderId: '689893375587',
    projectId: 'demo1-2ad94',
    storageBucket: 'demo1-2ad94.appspot.com',
    iosBundleId: 'com.example.loginFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCHvmV6RejMeqxTTbMlmqrlCzp7F7pThk',
    appId: '1:689893375587:ios:95d2afa289d53c811a4256',
    messagingSenderId: '689893375587',
    projectId: 'demo1-2ad94',
    storageBucket: 'demo1-2ad94.appspot.com',
    iosBundleId: 'com.example.loginFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVXnUG9hcRu2bn2PukWFQmCJ9-eJU1OME',
    appId: '1:689893375587:web:ca2280448f3376251a4256',
    messagingSenderId: '689893375587',
    projectId: 'demo1-2ad94',
    authDomain: 'demo1-2ad94.firebaseapp.com',
    storageBucket: 'demo1-2ad94.appspot.com',
  );
}
